INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "1", "Arts", "Director", "Directors make many of the creative decisions that bring a dramatic production to life. They have a part in almost every aspect of producing a play, film, or TV program. They must be creative artists as well as knowledgeable technicians. Active onstage and behind the scenes, they interpret scripts, communicate their vision to set and costume designers, audition and select cast members, manage rehearsals, and coach actors." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "2", "Arts", "Graphic Designer", "If you’re fascinated by the differences between the fonts Times New Roman and Geneva -- or simply enjoy arranging photos on a page -- you may have a future in graphic design. One of the most practical paths for artsy people, graphic design requires not only a good eye but an ability to use the computer as a tool for achieving your vision." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "3", "Arts", "Web Designer", "Do you prefer Google or Yahoo? The websites in your favorites list are there for a reason -- probably a combination of visual appeal and usability. Creating that perfect combination is what Web designers do for a living. By using type (lettering), images, and other visual devices, Web designers create a digital playground where consumers can find the information they need while enjoying the ride." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "4", "Business", "Financial Analyst", "Do you get psyched about stocks and bonds? Is the business section the first place you flip to in the Sunday paper? If so, then you should think about becoming a financial analyst. <br>If you do, your main responsibility will be spotting stock market trends and keeping tabs on up-and-coming companies. You’ll also make predictions about the economic health of various industries. Why? So you can help businesses make good investment decisions." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "5", "Business", "Personal Finance Advisor", "If you’ve ever given a friend advice on how to spend money, then you’ve already acted the part of personal financial advisor. <br>But knowing how to spend isn’t the only skill you’ll need to have. You’ll have to know about saving as well. Maybe your friend has been saving up for college but suddenly decides to splurge on an expensive new stereo. Can you convince him to keep saving for school?" );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "6", "Business", "Advertising Sales Agent", "Advertising sales agents hold a wide range of jobs. Local sales agents work for specific media companies, such as newspapers and radio stations, selling ad space or airtime to local businesses. Other agents work in the advertising industry for companies that specialize in selling advertising and work on national ad campaigns. They act as go-betweens, bringing together businesses that need to advertise with media companies that have advertising to sell. <br>Instead of selling just one kind of advertising, sales agents often sell groups of ads that take advantage of a mix of media. These so-called integrated packages are a growing trend in the ad biz. A single package might include space in a magazine and on a website, along with TV airtime." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "7", "Business", "Stockbroker", "What’s the right combination of investments for someone just out of college? How about someone nearing retirement? What effect will higher unemployment rates have on certain stocks? Under what economic conditions is it wise to buy government bonds instead of stocks? <br>If questions like these -- as well as a little risk and a lot of responsibility -- appeal to you, consider a career as a broker or financial services sales agent." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "8", "Health and Medicine", "Medical Assistant", "Medical assistants are often the backbone of doctors’ offices. <br>Some assistants sit at the front desk and check patients in when they arrive for an appointment. Others show patients to the exam room, take histories, prepare them for the doctor’s exam, and even assist during the exam. Still other assistants handle insurance forms and referrals or billing. In some small practices, medical assistants may handle all of the above -- and more." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "9", "Health and Medicine", "Psychiatrist", "The granddaddy of psychiatry is Sigmund Freud, born in 1856. Freud came up with many concepts that are now a part of psychiatry -- and of popular culture. These include the ego, the unconscious, the slip of the tongue, and repression. Freud invented psychoanalysis ("the talking cure"). And he didn't just talk the talk; he walked the walk, doing self-analysis to test out his ideas. <br>Although many of his controversial ideas have been rejected by today’s psychiatrists, Freud left behind a body of work that still grips our cultural imagination." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "10", "Health and Medicine", "Radiologist", "Since the invention of the x-ray more than one hundred years ago, the ability to see inside the human body has enabled doctors to understand how our bodies work -- and how they don’t. <br>But we’ve come a long way in the last century. Health professionals now use a combination of techniques involving computers, sound waves, magnetism, and more. They can scan our bones, muscles, and organs with remarkable accuracy and diagnose and treat diseases and injuries as never before." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "11", "Health and Medicine", "Registered Nurse", "TV programs portray nurses as the backbone of a hospital. They pick up the slack when medical students are lost and often go beyond the call of duty to meet patient needs. Nursing may not always be as exciting as it seems on TV, but there’s truth to these dramas. <br>No less important is the work of registered nurses (RNs) in home care and nursing home settings.  Regardless of where they’re employed, RNs play a critical role helping doctors take care of patients." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "12", "Health and Medicine", "Veterinarian", "If you’ve ever pulled a thorn from a dog’s paw, you know the satisfaction that comes from making an animal feel better. But if you’ve ever given a cat a pill, you also know that it’s not easy to tell an animal what’s best for it. <br>As a veterinary student, you’ll learn about more than the health problems of animals. You'll also learn how to diagnose patients who can’t explain their own symptoms. <br>You may be surprised to learn that people skills are a must for veterinarians. That's because for every animal a vet treats, there's a human standing by. In fact, one of the hardest things vets have to do is tell someone it’s time to let go of a sick pet." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "13", "Media and Social Sciences", "Clinical Psychologist", "Have you ever heard the term "stream of consciousness"? We use it to describe words that flow nonstop, following a person's thoughts as they move freely from one topic to the next. The term was created by William James, who is considered one of the fathers of psychology. <br>With gentle guidance from skilled clinical psychologists, people can ride their stream of consciousness to surprising memories and insights. These memories and insights often play a key role in healing." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "14", "Media and Social Sciences", "Interpreter", "From courtrooms to boardrooms, interpreters help people who speak different languages understand each other. They work in a range of situations, from business meetings to criminal trials to medical emergencies. Those who know American Sign Language interpret spoken language to sign language and vice versa. Since interpreters work on the spot and can’t go back to correct any mistakes they make, they need intense concentration." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "15", "Media and Social Sciences", "Technical Writer", "Computer software and hardware, cars, stereos, and many other products come with instructions. Technical writers create operating instructions and other informational material, such as maintenance manuals, catalogs, parts lists, and assembly instructions. <br>This information not only allows consumers to use and maintain products easily and safely, but also protects manufacturers from being sued. If you enjoy writing and are curious about developments in science and technology, this field might be for you." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "16", "Science, Math, and Technology", "Aerospace Engineer", "In 1903, the Wright brothers’ first plane flew for twelve seconds and went only 120 feet. Today, aerospace engineers are working on supersonic ramjets. These scramjets, as they’re called, will take you from New York to Tokyo in only two hours. That’s a lot of progress for one century. <br>As an aerospace engineer, you could build satellites or defense systems. You could make airplanes faster and safer. You could design a spacecraft, a space station, or an explorer robot like the Mars-roving Spirit. If looking up at the sky starts you thinking about how to get there, you could be one of tomorrow’s aerospace engineers." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "17", "Science, Math, and Technology", "Chemist", "You may not realize it, but the products of chemistry play a big role in our daily lives. Chemists and materials scientists create the building blocks for medicines like Prozac or products such as plastic bags. Even the chocolate, marshmallow, and banana flavors of the processed food you eat were created in a lab by food chemists. <br>Chemists and materials scientists working in applied research come up with new products for industrial, commercial, and medical use." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "18", "Science, Math, and Technology", "Computer Programmer", "If you picture yourself as a computer programmer, you may already know a computer language. Once you know multiple computer languages, you’ll be able to communicate throughout the world. <br>In addition to mastering programming languages like C++ and Java, you’ll also need to communicate easily with people. After all, you’ll often work with a team and sometimes with the users of the products you develop. At the end of the day, the key to programming is language." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "19", "Science, Math, and Technology", "Database Administrator", "When you created a My Organizer account on this website, you answered questions about yourself and came up with a password. But where does all that information go? How is it stored and then promptly retrieved each time you log in? <br>Just ask our database administrators. Thanks to their efforts, your data and the data of thousands of other users remains secure and accessible." );

INSERT INTO career_category ( id, career, subcareer, description ) VALUES ( "20", "Science, Math, and Technology", "Wildlife Technician", "Wildlife technicians do whatever it takes to help wildlife biologists and conservation scientists. These scientists make management decisions about wild animals and natural resources. Technicians help them gather data and carry out their plans. <br>As a wildlife technician, you might track, trap, and tag animals or take surveys of them from a small plane. You might plant native grasses to restore a natural area or extract eggs in a fish hatchery. You might travel on snowshoes, work on a boat, or handle an all-terrain vehicle. Whatever tasks you do, you'll help wildlife professionals make smart decisions that will affect the Earth's future." );
