INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "1", "Arts/Humanities", "Digital Production", "The work of a great choreographer re-created with hand-drawn 3-D figures, a multimedia representation of the mind of a child with learning disabilities, an electronic “concert” shaped by the artist’s own brain waves and heartbeat -- these are a few of the projects created by today’s cutting-edge digital artists. The digital arts have been described as the place where artistry and technology meet. If you are a creative person who loves technology, a major in digital arts could be the right choice for you. <br>You’ll learn how to use a wide variety of digital animation programs, including 2-D and 3-D graphics programs, and explore electronic music, video installation, and Web design. You’ll also study the history and theory of digital media and work on perfecting basic art skills in foundation courses such as drawing, design, and color theory." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "2", "Arts/Humanities", "Think of your favorite movie. Was it the story you liked? Or the characters? The action? How about the look of it? Digging deep into your gut feelings about movies is just the beginning of film studies. <br>If movies mean more to you than just an evening out with your friends, this could be the major for you. You’ll learn how to discuss and write about films critically. You’ll also learn about the connections movies have to history and national identities. You’ll even learn what all those people listed in the credits actually do. P.S. A gaffer is a lighting technician." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "3", "Arts/Humanities", "Photography", "What makes an object beautiful? How can that same object be shown in a disturbing light? How has the camera evolved throughout the last century, and what impact have these changes had on the art world? Can a photograph created for business purposes, such as a billboard, ever transcend commerce and become art? As a photography major, you'll explore such ideas. <br>Of course, you’ll spend much of your time practicing the art of photography. You’ll learn the basics of composition, color balance, and the use of light. You’ll also experiment in the darkroom, practicing a range of techniques to control the way your image impacts the viewer." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "4", "Arts/Humanities", "English", "If you love to curl up with a good book, then majoring in English might be for you. But there's a lot more to studying English than just reading novels, short stories, plays, and poetry by English-speaking writers. You'll have to examine what you read and come up with opinions about it. For example, you might have to explain a book's main theme or show what it reveals about cultural stereotypes. You'll then have to share your views in class discussions and in papers. <br>One of the great things about majoring in English is that you can bring your personal interests into your studies. For instance, you can focus on the literature of a certain time period, location, or author." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "5", "Arts/Humanities", "Philosophy", "Philosophy dates back to ancient times when Confucius and Plato walked the earth. Yet it is very much alive today in such questions as whether or not computers think. Philosophers question issues that others either take for granted or find too difficult to ponder. If you choose this major, you'll find yourself asking everything from why we should be good to how we know what we know. You'll even question your own questions. <br>Some philosophy undergrads become philosophers. But most by far build careers in other areas, such as law. And thanks to all that pondering, all develop great skills in logic, problem solving, and creative thinking that pay off in any field." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "6", "Arts/Humanities", "Religous Studies", "How can religion lead both to the activism of Gandhi, Mother Teresa, and Dr. Martin Luther King, Jr., and to cult suicides? How was the universe created? Do we have souls? Religious studies majors explore such questions -- but they don't settle for simple answers. Instead, they seek rich insights through research, reading, writing, and discussion. <br>Whatever their differences, most religious studies majors agree that, as one student put it, "we are really one people; we just have different ways of expressing truth." If you are fascinated by religious questions and traditions, and enjoy exploring many points of view, consider this major." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "7", "Business", "Accounting", "If you're a big baseball fan, you know that keeping track of how well your favorite team plays and predicting how it will do in the future is part of the fun. In businesses, government agencies, and nonprofits, accountants often engage in very similar activity. <br>Not simply bean counters, accountants analyze financial information and consult with upper management about important business decisions. Of course, some accountants also keep the books, recording every financial transaction." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "8", "Business", "Business Management", "With the creation of large factories in the late 1800s came the need to manage large groups of workers. In his 1911 book The Principles of Scientific Management, Frederick Winslow Taylor addressed that need. He suggested that each worker be trained to do a single task with no wasted effort. His philosophy made such a big impact on the business world that it was nicknamed Taylorism and is still studied today. <br>Of course, there’s a lot of disagreement about Taylorism: some people argue that it's inhumane, while others celebrate the increased productivity it has led to. As a student in business management, you’ll add your voice to this debate and others like it." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "9", "Business", "Hospitality Administration", "As a train traveler headed out West in 1875, you would have had trouble finding a decent meal or a place to rest your head. But Fred Harvey changed all that. He started a chain of restaurants and hotels where clean and polite waitresses served tired travelers everything from oysters to duck and olives to ice cream. <br>You might say that Harvey tamed the Wild West, making it more hospitable (welcoming and pleasant) to travelers. If you study hospitality management, you'll prepare to follow in his footsteps." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "10", "Business", "Human Resources", "Back in the late 1800s the idea at the cutting edge of business was that people work like machines. If you gave them the right tools and told them exactly how to do their job, they would work better. Since then, human resources has come a long way. People are recognized as psychologically complicated individuals at the heart of every organization. If you major in human resources management, you’ll study people and the workplace  -- and you’ll learn what it takes to meet the needs of people in the workplace." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "11", "Business", "Business (General)", "Handheld computers and cell phones make business dealings easier and faster. But there's a downside. Because these devices are easily lost, there's a risk that private information will fall into the wrong hands. Executives using cell phones in airports or other public places may forget to avoid discussing confidential topics. To make matters worse, competitors could also use technology to listen in. <br>How can we ensure that the cons of new technology don’t outweigh the pros? If you major in business, you’ll learn a wide range of business skills and study the issues affecting today's business climate." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "12", "Business", "Real Estate", "When you and your friends have game night, do you always want to play Monopoly? And once you’ve snatched up Park Place and Broadway, are you the type of player who will wheel and deal until you’ve built hotels everywhere? If so, you may want to study real estate.
Real estate professionals are the masters of buying and building property all over the world. These business people know how to make investments pay off, and once you graduate you’ll be ready to join them." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "13", "Health and Medicine", "Nursing", "It’s a typical morning at a city hospital. A woman arrives complaining of severe stomach pain. A nurse asks her a series of direct questions about her symptoms and learns what may be causing the pain. The nurse alerts a doctor, and they work together to order tests and begin treatment. Upstairs, a second nurse administers chemotherapy drugs to a patient who suffers from cancer. On another floor, a third nurse helps to deliver a baby. <br>If you study nursing, you may train in a hospital like this where nurses care for, educate, and enhance the lives of patients every day. You’ll learn about everything from examining patients and treating their immediate needs to keeping up the health of people with long-term conditions." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "14", "Health and Medicine", "Pharmaceutical Science", "In the early 1940s, tuberculosis was still a killer with no effective treatment; hundreds of thousands died in 1942 alone. But that changed when Selman Waksman and his colleagues, working with soil, isolated streptomycin, a new type of antibiotic. Although it was later found that it takes a combination of drugs to cure tuberculosis, streptomycin was the first to fight the disease. Waksman earned a Nobel Prize for his work. <br>Such breakthroughs don’t happen every day. But if you’d like to be involved in the research, testing, and manufacture of new drugs, a pharmaceutical sciences major will give you the knowledge and skills you need. Who knows? Maybe you’ll be on another history-making team." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "15", "Health and Medicine", "Public Health", "As medicine continues to advance, so do disease and poverty. In recent years we’ve seen the devastating effects worldwide of infectious diseases like AIDS and tuberculosis. <br>If you study public health, you’ll learn how government actions; access (and lack of access) to health care; communication and education; and funding all factor into the spread, treatment, and prevention of disease. Your course work will cover epidemiology (the science concerned with the spread and control of disease), preventive medicine, health economics, and health ethics." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "16", "Health and Medicine", "Sports Medicine", "Sports medicine programs are hospital residencies (on-the-job training) for graduates of medical school who have already completed a residency in orthopedic surgery. Sports medicine residents learn about athletic injuries while treating athletes under a doctor’s supervision. They learn about acute and chronic injuries, diagnosis, and therapy and rehabilitation." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "17", "Science, Math, and Technology", "Architecture", "While architecture is grounded in science, its heart is in the arts. Well-designed buildings not only serve the people who use them. They are also works of art that help define the town or city in which they stand. <br>As an architecture major, you'll learn how to work with others to imagine buildings, from straw-bale houses to the tallest skyscrapers. And with the technical know-how you pick up in such classes as architectural engineering and construction materials, you'll know just what needs to be done to bring them to life." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "18", "Science, Math, and Technology", "Biochemistry", "When you look at a plant or an animal, be it a majestic redwood, your golden retriever, or even another person, you see the entire organism, a smoothly functioning whole. <br>But beneath the surface is a living machine. At scales much too small for us to see with the naked eye, there are chemical reactions going on that enable organisms to live. For example, when you eat, proteins called enzymes help speed up the chemical reactions that break down food so that you can get the energy you need to live. If you major in biochemistry, you’ll examine these and other chemical reactions." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "19", "Science, Math, and Technology", "Biology", "When you think of life on earth, your first thoughts are probably about familiar animals, your pet dog or cat, the bird you see in the tree outside your window. But that is really only a small sample of all the types of life on our planet, which include plants, bacteria, fungi, and animals in a vast array of body forms and types. <br>Biology is the study of life, individual organisms, their communities, and the systems, cells, and processes that make up living matter." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "20", "Science, Math, and Technology", "Neuroscience", "Everyone gets stressed out now and then, and some stress is healthy. Say a dad sees his toddler toppling off a play structure. His brain releases chemicals that trigger other reactions in his body, giving him a burst of energy to dash to his daughter before she hits the pavement.
But neuroscientists have found that too much stress can hurt a part the brain’s hippocampus, which plays a key role in memory. Neuroscientists are working on treatments for stress -- but the best remedy may be to just mellow out. If you major in neuroscience, you’ll study stress, memory, and other mysteries of the brain and nervous system." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "21", "Science, Math, and Technology", "Computer and Information Technology", "Students in this major study a broad range of computer topics rather than focusing on more specific majors in this field. Once you’ve studied different types of computer and information technologies, you may decide to become an expert in one area." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "22", "Science, Math, and Technology", "Engineering", "In order to build the Pantheon, the world’s largest dome for over a thousand years, the Romans carved an oculus, or opening, at the top to lighten the load. Engineers still take on projects like the Pantheon. But they also work on everything from robots small enough to fit into the human body to new ways of breaking the sound barrier. <br>A general engineering major at the associate’s degree level provides solid preparation for any type of engineering degree at the bachelor’s level. And if you decide to earn a bachelor’s degree in general engineering, you will study many different fields of engineering and business. You could then go on to coordinate teams of engineers, oversee product development from invention to market, or use your engineering know-how in a nonengineering field, such as law or medicine." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "23", "Science, Math, and Technology", "Mathematics", "Most of us are comfortable using everyday math -- when we go shopping, for example. But higher level math, such as calculus, may seem mysterious, a completely unfamiliar language. As a math major, you’ll study this language and learn how to use it to describe the world. You’ll explore calculus, modern algebra, and other high-level math in the purest light.<br>If you love to solve math problems just to know the answer and enjoy using abstract concepts to discover whether something is true or false, this could be the major for you." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "24", "Social Sciences", "Journalism", "Are you someone who can’t get enough of the latest headlines? Do you love the thrill of the chase? If so, you may want to consider majoring in journalism. With this degree, you could find yourself covering world events for a major newspaper or TV network, reporting on sports for a local radio station, or writing about entertainment on the Internet. <br>As a journalism major, you’ll not only master the art of reporting and writing, but you'll also learn about libel and other legal issues that affect the media. And you'll learn what it takes to survive in a tough, but often rewarding, business." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "25", "Social Sciences", "Education", "Do you find yourself reading stories to younger kids or organizing games for your cousins at the family picnic? Do you feel proud when you've explained a difficult math problem to a friend and his face lights up with understanding? <br>If you major in education, you’ll develop your talents into the skills every teacher needs. You’ll find out how to set up and manage a classroom, design and teach inspiring lessons, and help students succeed no matter what their age, background, or learning style." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "26", "Social Sciences", "History", "You’ve probably heard older people talk about the “good old days.” But were they really all that good? Were people and ideas all that different? How did the good old days become today? <br>To answer questions like these, you’ll need to look for clues -- and not only in textbooks filled with dates and biographies. As a history major, you’ll find history in everything from a 1956 Elvis Presley poster to a 1934 ticket stub showing the price of a movie. You’ll even find it in last summer’s playlist of your favorite songs. <br> By the time you graduate, you’ll know how to decide for yourself what to think about the old days -- good or bad. And, perhaps more importantly, you’ll learn what those days can teach us about today and tomorrow." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "27", "Social Sciences", "Psychology", "If psychology interests you, you have something in common with the ancient Greek philosophers. They asked questions about the life of the mind: What is the relationship between mind and body? How can we tell if the world is really the way we think it is? <br>Today's psychologists study all sorts of fascinating questions, such as the following: Why is learning a language as an infant easier than as a teenager? What are the roots of violence? What is the best way to help someone with an eating disorder like anorexia?" );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "28", "Social Sciences", "Criminology", "Our obsession with crime and punishment is reflected in fact and fiction television programs about on-the-lam killers, petty criminals, and white-collar crime. Today, as much as ever, we are fascinated by questions about crime: Why do people commit crimes? Is there such a thing as a born killer? Is a completely crime-free society possible? <br>Criminology is the search for answers to questions like these. Our understanding of who commits crimes and why has a direct influence on the criminal-justice system. As a criminology student, you may come up with new theories that lead to better responses to crime and its causes." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "29", "Social Sciences", "Sociology", "Picture your high school cafeteria for a moment. It’s not just one giant group of students hanging out together, is it? There are probably more than a few cliques. <br>Have you ever wondered how these cliques form? Or why some kids are more popular than others? Or why people act one way at home and a completely different way at school? If you want to explore questions like these, consider majoring in sociology." );

INSERT INTO major_category ( id, major, submajor, description ) VALUES ( "30", "Social Sciences", "Political Science", "Politics affects the air we breathe, the schools we attend, the jobs we do, the communities we live in, and the taxes we pay. If you choose this major, you’ll learn the principles at work behind the decisions that affect every aspect of our lives. <br>Whether they're conservative or liberal, cynical or idealistic, one common characteristic among political science and government majors is their addiction to politics. If active engagement in the political system is for you, a political science major is a great way to get started." );

